#!/usr/bin/env bash
# Update package lists and install nginx with "-y" to automatically confirm installation prompts
apt-get update
apt-get install -y nginx

# Ensure nginx is listening on port 80
sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default

# Create a temporary index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart nginx without systemctl
/etc/init.d/nginx restart

