#!/usr/bin/env bash
# config a new Nginx server so for /redirect_me

apt-get -y update
apt-get -y install nginx
first_location='\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
sed -i "/server_name _;/ a \ $first_location" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
