#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt update
sudo apt install haproxy -y
#sudo wget -q -O /etc/nginx/nginx.conf https://exampleconfig.com/static/raw/nginx/ubuntu20.04/etc/nginx/nginx.conf
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 54.237.62.80:80 check\n\tserver server2 54.236.33.150:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
