#!/usr/bin/env bash
# Print Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Printnumber of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

mifil="apache-access.log"
awk -F' ' '{ print $1, $9}' $mifil | sort | uniq -c|sort -nr
